version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ProjectFlow.Api/Dockerfile
    ports:
      - "8080:8080" 
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=ProjectFlowDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      db: 
        condition: service_healthy 

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "${DB_PASSWORD}" 
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '${DB_PASSWORD}' -Q 'SELECT 1' || exit 1"]
        interval: 10s
        timeout: 3s
        retries: 10
        start_period: 10s